/** ChemLab application composition root. */
import { createRouter } from './router.js';
import { contentService } from './content-service.js';
import { MasteryService } from './mastery-service.js';
import { createProgressProjection } from './progress-projection.js';
import { AssessmentRuntimeController } from '../controllers/assessment-runtime-controller.js';
import { ExperimentController } from '../controllers/experiment-controller.js';
import { LearningController } from '../controllers/learning-controller.js';
import { renderHome } from '../views/home-view.js';
import { renderV19Course } from '../views/v19-course-view.js';
import { renderQuiz, renderQuizResult } from '../views/quiz-view.js';
import { renderV19Experiment, renderV19ExperimentResult } from '../views/v19-experiment-view.js';
import { renderDashboard } from '../views/dashboard-view.js';
import { renderGraph } from '../views/graph-view.js';
import { renderRemediation } from '../views/remediation-view.js';
import { renderAITutorPage } from '../frontend/pages/ai-tutor/ai-tutor-page.js';
import { renderCoursePortal } from '../frontend/pages/course/course-portal-page.js';
import { renderLabPortal } from '../frontend/pages/lab/lab-portal-page.js';
import { renderKnowledgePortal } from '../frontend/pages/knowledge/knowledge-portal-page.js';
import { renderAssessmentPortal } from '../frontend/pages/assessment/assessment-portal-page.js';
import { renderProgressPortal } from '../frontend/pages/progress/progress-portal-page.js';
import { createRemediationCatalog } from '../core/diagnosis/remediation-catalog.js';
import { getLessonReleaseState } from '../content/release-policy.js';
const getDefaultRoot=()=>typeof document==='undefined'?null:document.querySelector('#app-root');
const CANONICAL_GOLDEN_LESSON='lesson-01-material-changes-properties';
export function createApplication({state,assessment,experimentEngine,masteryService=new MasteryService(),root=getDefaultRoot()}={}){
 const learning=new LearningController({contentService,state,remediationCatalog:{}});
 const controllers={learning,assessment:new AssessmentRuntimeController({assessment,contentService,state,masteryService,learningController:learning}),experiment:new ExperimentController({experimentEngine,state,masteryService,learningController:learning})};
 const views={renderHome,renderCourse:renderV19Course,renderQuiz,renderQuizResult,renderExperiment:renderV19Experiment,renderExperimentResult:renderV19ExperimentResult,renderDashboard,renderGraph,renderRemediation,renderAITutorPage};
 let hydrationPromise=null,stopped=false;
 const router=createRouter({onRoute:route=>{state.route=route;},render:route=>renderRoute(route)});
 const currentTerm=()=>typeof window!=='undefined'&&window.chemLabTextbookTerm==='lower'?'lower':'upper';
 function renderHomeLoading(){if(!root)return;views.renderHome({root,data:{title:'九年级化学智能学习中心',subtitle:'正在准备学习内容…',lessons:[],stats:{completed:0,mastery:0,questions:0}},onCourse:()=>router.navigate('course'),onDashboard:()=>router.navigate('progress'),onGraph:()=>router.navigate('knowledge-map')});}
 async function hydrateContent(){if(hydrationPromise)return hydrationPromise;hydrationPromise=contentService.load().then(data=>{learning.remediationCatalog=createRemediationCatalog(data);state.contentReady=true;state.contentLoadError=null;if(!stopped)renderRoute(router.current());return data;}).catch(error=>{state.contentLoadError=error;state.contentReady=false;if(root&&!stopped&&router.current().page==='home')views.renderHome({root,data:{title:'九年级化学智能学习中心',subtitle:'课程内容暂时无法加载，请刷新后重试。',lessons:[],stats:{completed:0,mastery:0,questions:0}},onCourse:()=>router.navigate('course'),onDashboard:()=>router.navigate('progress'),onGraph:()=>router.navigate('knowledge-map')});throw error;});return hydrationPromise;}
 async function getHomeData(){if(!contentService.data)return null;const progress=createProgressProjection({...state.progress,mastery:masteryService.getState()});const lessons=(await contentService.getLessons({semester:currentTerm()})).filter(day=>Boolean(day.canonicalId)).sort((a,b)=>Number(a.day||0)-Number(b.day||0)).map(day=>{const lessonId=day.canonicalId;const release=getLessonReleaseState(day);const stateView=controllers.learning.getLessonCardState({...day,id:lessonId});return({...day,id:lessonId,completed:Boolean(progress.completed?.[lessonId]),phase:stateView.phase,cardLabel:stateView.available?`${stateView.label} · ${release.label}`:release.label,available:stateView.available,releaseStatus:release.key});});const weakPoints=lessons.flatMap(lesson=>controllers.learning.getLessonState(lesson.id).diagnosis?.weakPoints||[]);return{title:'九年级化学智能学习中心',subtitle:'学习 → 实验 → 答题 → 诊断 → 补救 → 再检测 → Mastery',lessons,term:currentTerm(),hasRemediation:weakPoints.length>0,stats:{completed:lessons.filter(day=>day.completed).length,mastery:Math.round((progress.masteryScore||0)*100),questions:progress.questions||0,weak:new Set(weakPoints).size}};}
 async function renderRoute(route){if(!root)return;const needsContent=['home','course','progress','assessment','quiz','knowledge-map','graph'].includes(route.page);if(needsContent&&!state.contentReady){if(route.page==='home')renderHomeLoading();return;}const data=['home','course','progress','assessment'].includes(route.page)?await getHomeData():null;
  if(route.page==='home')return views.renderHome({root,data,onCourse:id=>router.navigate('course',id||firstIncompleteLesson(data)),onDashboard:()=>router.navigate('progress'),onGraph:()=>router.navigate('knowledge-map'),onRemediation:()=>router.navigate('assessment')});
  if(route.page==='course'&&!route.params.length)return renderCoursePortal({root,lessons:data?.lessons,term:currentTerm(),onLesson:id=>router.navigate('course',id),onHome:()=>router.navigate('home')});
  if(route.page==='course'){const lessonId=route.params[0]||firstIncompleteLesson(data)||CANONICAL_GOLDEN_LESSON;const lesson=await controllers.learning.getLesson(lessonId);if(!lesson)return views.renderCourse({root,lesson:{id:lessonId,title:'课程未找到',description:'请返回学习中心选择课程。'}});const guidedLearning=await contentService.getGuidedLearning(lesson.id||lessonId);const lessonState=controllers.learning.getLessonState(lessonId);const phase=controllers.learning.getLessonPhase(lessonId);const stages=controllers.learning.getStageAvailability(lesson,guidedLearning);const masteryState=controllers.learning.getLessonMastery(lessonId);return views.renderCourse({root,lesson,guidedLearning,lessonState,phase,stages,progress:controllers.learning.getProgress(lessonId),masteryPassed:masteryState?.status==='passed',diagnosis:lessonState.diagnosis||{},diagnosticQuestions:Array.isArray(lesson.diagnosticQuestions)?lesson.diagnosticQuestions:[],highlightStep:route.params[1]||'',onGuidedCheck:(id,stepId,result)=>{controllers.learning.recordGuidedCheck(id,stepId,result);void renderRoute(route);},onStartQuiz:()=>router.navigate('quiz',lessonId),onStartMastery:()=>router.navigate('quiz',`mastery:${lessonId}`),onStartExperiment:id=>router.navigate('experiment',id),onStartRemediation:()=>router.navigate('remediation',lessonId),onStartTransfer:()=>router.navigate('quiz',`transfer:${lessonId}`),onComplete:()=>{if(controllers.learning.markComplete(lessonId,lesson))void renderRoute(route);},onBack:()=>router.navigate('course')});}
  if(route.page==='lab'&&!route.params.length){const experiments=await contentService.getExperimentCatalog({semester:currentTerm()});return renderLabPortal({root,experiments,onHome:()=>router.navigate('home'),onExperiment:experiment=>{if(experiment?.id)router.navigate('experiment',experiment.id);}});}
  if(route.page==='knowledge-map'){const graph=await contentService.getKnowledgeGraphViewModel().catch(()=>({nodes:[],relations:[]}));const homeData=await getHomeData();return renderKnowledgePortal({root,onHome:()=>router.navigate('home'),onLearn:lessonId=>router.navigate('course',lessonId),nodes:graph?.nodes||[],relations:graph?.relations||[],lessons:Array.isArray(homeData?.lessons)?homeData.lessons:[]});}
  if(route.page==='assessment'){const progress=createProgressProjection({...state.progress,mastery:masteryService.getState()});const tasks=[];for(const lesson of data.lessons||[]){const lessonId=lesson.canonicalId;const lessonState=controllers.learning.getLessonState(lessonId);const fullLesson=await controllers.learning.getLesson(lessonId);const stages=controllers.learning.getStageAvailability({...lesson,...fullLesson,id:lessonId},await contentService.getGuidedLearning(lessonId));if(stages.practice&&!lessonState.practice&&Array.isArray(fullLesson?.questions)&&fullLesson.questions.length)tasks.push({id:`practice:${lessonId}`,title:`${lesson.title} · 基础练习`,description:'完成本课基础练习并生成诊断证据。',label:'开始练习'});if(lessonState.remediation?.status==='needs-remediation')tasks.push({id:`remediation:${lessonId}`,title:`${lesson.title} · 针对性补救`,description:'复习薄弱点并完成定向再检测。',label:'继续补救'});if(stages.mastery&&!lessonState.mastery&&fullLesson?.mastery?.resourceRef)tasks.push({id:`mastery:${lessonId}`,title:`${lesson.title} · Mastery`,description:'通过陌生情境题检验是否达到掌握标准。',label:'开始掌握测试'});}return renderAssessmentPortal({root,onHome:()=>router.navigate('home'),score:Math.round((progress.masteryScore||0)*100),weakPoints:state.learning?.diagnosis?.weakPoints||[],tasks,onTask:task=>{if(!task)return;if(task.id.startsWith('practice:'))router.navigate('quiz',task.id.slice(9));else if(task.id.startsWith('mastery:'))router.navigate('quiz',task.id);else if(task.id.startsWith('remediation:'))router.navigate('remediation',task.id.slice(12));}});}
  if(route.page==='progress'||route.page==='dashboard'){const progress=createProgressProjection({...state.progress,mastery:masteryService.getState()}),graph=await contentService.getKnowledgeGraphViewModel().catch(()=>({nodes:[]}));return renderProgressPortal({root,onHome:()=>router.navigate('home'),onQuiz:id=>router.navigate('quiz',id),summary:{completed:Object.values(progress.completed||{}).filter(Boolean).length,mastery:Math.round((progress.masteryScore||0)*100),questions:progress.questions||0},masteryState:masteryService.getState(),knowledgeNodes:graph?.nodes||[],weakPoints:state.learning?.diagnosis?.weakPoints||[]});}
  if(route.page==='graph')return views.renderGraph({root,graph:await contentService.getKnowledgeGraphViewModel(),onBack:()=>router.navigate('home')});
  if(route.page==='quiz'){const raw=route.params[0]||firstIncompleteLesson(await getHomeData());const text=String(raw||'');let mode='practice';let lessonId=text;if(text.startsWith('mastery:')){mode='mastery';lessonId=text.slice(8);}if(text.startsWith('recheck:')){mode='recheck';lessonId=text.slice(8);}if(text.startsWith('transfer:')){mode='transfer';lessonId=text.slice(9);}const lessonState=controllers.learning.getLessonState(lessonId);if(mode==='practice'&&!controllers.assessment.hasSession(lessonId,'practice'))await controllers.assessment.startPractice(lessonId);if(mode==='mastery'&&!controllers.assessment.hasSession(lessonId,'mastery'))await controllers.assessment.startMastery(lessonId);if(mode==='recheck'&&!controllers.assessment.hasSession(lessonId,'recheck'))await controllers.assessment.startRecheck(lessonId,lessonState.recheck?.knowledgeIds||lessonState.diagnosis?.weakPoints||[]);if(mode==='transfer'&&!controllers.assessment.hasSession(lessonId,'transfer'))await controllers.assessment.startTransfer(lessonId);const session=controllers.assessment.session;if(!session||session.lessonId!==lessonId||session.mode!==mode)return router.navigate('course',lessonId);if(session.completed){const score=controllers.assessment.getScore();const result=mode==='mastery'?lessonState.mastery:mode==='recheck'?lessonState.recheck:mode==='transfer'?lessonState.transfer:lessonState.practice;return views.renderQuizResult({root,score,correct:session.answers.filter(a=>a.correct).length,total:session.answers.length,hasRemediation:mode==='mastery'?result?.status!=='passed':lessonState.remediation?.status==='needs-remediation',onRemediation:()=>router.navigate('remediation',lessonId),onContinue:()=>router.navigate('course',lessonId),status:result?.status,mode,lessonId,answers:session.answers,questions:session.questions});}return views.renderQuiz({root,question:session.questions[session.index],index:session.index,total:session.questions.length,mode,onAnswer:optionIndex=>{if(controllers.assessment.answer(optionIndex))renderRoute(route);}});}
  if(route.page==='experiment'&&!route.params.length)return renderLabPortal({root,onHome:()=>router.navigate('home')});
  if(route.page==='experiment'){const experiment=await contentService.getExperiment(route.params[0]);if(experiment)controllers.experiment.register(experiment);if(!controllers.experiment.session&&!controllers.experiment.start(route.params[0]))return router.navigate('course',experiment?.lessonId||CANONICAL_GOLDEN_LESSON);const session=controllers.experiment.session;return views.renderExperiment({root,experiment:session.experiment||{},session,onNext:()=>{controllers.experiment.next();renderRoute(route);},onObserve:text=>controllers.experiment.observe(text),onComplete:()=>views.renderExperimentResult({root,result:controllers.experiment.complete()||{},onContinue:()=>router.navigate('course',session.experiment?.lessonId||CANONICAL_GOLDEN_LESSON)})});}
  if(route.page==='remediation'){const lessonId=route.params[0]||state.learning?.diagnosis?.lessonId||CANONICAL_GOLDEN_LESSON;const lessonState=controllers.learning.getLessonState(lessonId);const plan=lessonState.remediation||state.learning?.remediation;const lesson=await controllers.learning.getLesson(lessonId);const guidedLearning=await contentService.getGuidedLearning(lesson?.id||lessonId);return views.renderRemediation({root,plan,lessonId,guidedLearning,onRecheck:async selectedPlan=>{const ids=(selectedPlan?.steps||[]).find(step=>step.type==='recheck')?.knowledgeIds||lessonState.diagnosis?.weakPoints||[];if(await controllers.assessment.startRecheck(lessonId,ids))router.navigate('quiz',`recheck:${lessonId}`);},onTransfer:async ()=>{if(await controllers.assessment.startTransfer(lessonId))router.navigate('quiz',`transfer:${lessonId}`);else router.navigate('course',lessonId);},onReview:stepId=>{router.navigate('course',lessonId,stepId);}});}
  if(route.page==='ai-tutor')return views.renderAITutorPage({root});if(route.page==='experiment-result'||route.page==='result')return router.navigate('progress');
 }
 return{state,router,contentService,masteryService,controllers,views,hydrateContent,start(){stopped=false;if(typeof window!=='undefined')window.addEventListener('chemlab:term-change',()=>{if(['home','course','lab','assessment','knowledge-map','progress'].includes(router.current().page))void renderRoute(router.current());});router.start();void hydrateContent().catch(()=>undefined);},stop(){stopped=true;router.stop();}};
}
function firstIncompleteLesson(data){return data?.lessons?.find(lesson=>!lesson.completed)?.id||data?.lessons?.[0]?.id||CANONICAL_GOLDEN_LESSON;}
