const NAV_ITEMS=[['home','首页','home'],['course','课程学习','course'],['lab','虚拟实验','lab'],['knowledge-map','知识地图','knowledge'],['assessment','训练中心','assessment'],['progress','学习报告','progress'],['ai-tutor','AI 化学导师','ai']];
const ICONS={home:'frontend/icons/home.svg',course:'frontend/icons/course.svg',lab:'frontend/icons/flask.svg',knowledge:'frontend/icons/atom.svg',assessment:'frontend/icons/chart.svg',progress:'frontend/icons/chart.svg',ai:'frontend/icons/robot.svg'};
function icon(name){return `<img class="chem-nav-icon" src="${ICONS[name]||ICONS.home}" alt="" aria-hidden="true">`}
export function mountPortalShell(root){
  if(!root)return null;
  root.className='chem-portal-root';
  root.innerHTML=`<div class="chem-shell"><aside class="chem-sidebar" aria-label="ChemLab 主导航"><button class="chem-brand" data-nav="home" aria-label="返回 ChemLab 首页"><img class="chem-brand-mark" src="frontend/icons/flask.svg" alt=""><span><strong>ChemLab</strong><small>Grade 9 Chemistry</small></span></button><div class="chem-sidebar-label">LEARNING</div><nav class="chem-nav" aria-label="学习模块">${NAV_ITEMS.map(([route,label,iconName])=>`<button class="chem-nav-item" data-nav="${route}" type="button">${icon(iconName)}<span>${label}</span></button>`).join('')}</nav><div class="chem-sidebar-bottom"><div class="chem-status-card"><span class="chem-status-dot"></span><span>学习系统正常</span></div></div></aside><div class="chem-workspace"><header class="chem-header"><button class="chem-menu-toggle" type="button" aria-label="打开导航" aria-expanded="false">☰</button><div class="chem-header-title"><span class="chem-mobile-title">ChemLab</span><span class="chem-breadcrumb">九年级化学 · 智能学习平台</span></div><div class="chem-header-actions"><button class="chem-search" type="button" data-nav="home" title="返回学习中心">⌕ <span>学习中心</span></button><button class="chem-ai-button" type="button" data-nav="ai-tutor">✦ AI Tutor</button></div></header><main id="chem-page-root" class="chem-page-root" tabindex="-1"><div class="chem-loading">ChemLab 正在启动…</div></main><footer class="chem-footer"><button type="button" class="chem-footer-home" data-nav="home">⌂ 返回首页</button><span>⚡ Chemistry Learning Runtime</span><span>Knowledge · Experiment · Assessment · Mastery</span></footer></div></div>`;
  const navigate=route=>{window.location.hash=route;root.querySelector('.chem-sidebar')?.classList.remove('open');root.querySelector('.chem-menu-toggle')?.setAttribute('aria-expanded','false')};
  root.querySelectorAll('[data-nav]').forEach(button=>button.addEventListener('click',()=>navigate(button.dataset.nav)));
  root.querySelector('.chem-menu-toggle')?.addEventListener('click',()=>{const sidebar=root.querySelector('.chem-sidebar');const button=root.querySelector('.chem-menu-toggle');const open=sidebar?.classList.toggle('open');button?.setAttribute('aria-expanded',String(Boolean(open)))});
  return root.querySelector('#chem-page-root');
}
export function syncPortalNavigation(root,route){if(!root)return;root.querySelectorAll('.chem-nav-item[data-nav]').forEach(item=>item.classList.toggle('active',item.dataset.nav===route?.page))}
